name: .NET Core Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: macos-latest  # Using macOS runner

    env:
      Solution_Name: ICT3112_Calculator.sln
      Unit_Test_Project_Path: ICT3112_Calculator.UnitTests/ICT3112_Calculator.UnitTests.csproj
      SpecFlow_Test_Project_Path: SpecFlowCalculatorTests/SpecFlowCalculatorTests.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Add step to list directory structure for troubleshooting
    - name: List directory structure
      run: |
        pwd
        ls -R

    # Install .NET Core SDK
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x

    # Restore dependencies
    - name: Restore dependencies
      run: dotnet restore ${{ env.Solution_Name }}

    # Build the solution
    - name: Build solution
      run: dotnet build ${{ env.Solution_Name }} --configuration ${{ matrix.configuration }} --no-restore

    # Run unit tests (use full path and ensure correct directory)
    - name: Run unit tests
      run: dotnet test ${{ env.Unit_Test_Project_Path }} --configuration ${{ matrix.configuration }} --verbosity normal

    # Run SpecFlow tests
    - name: Run SpecFlow tests
      run: dotnet test ${{ env.SpecFlow_Test_Project_Path }} --configuration ${{ matrix.configuration }} --verbosity normal
